- name: Stop nginx when reuquired
  hosts: all
  tasks:
    - name: Stop nginx when required
      service:
        name: nginx
        state: stopped
        enabled: false
      ignore_errors: yes

- name: Setup database and and webserver
  hosts: all

  roles:
    - role: geerlingguy.postgresql
    - role: geerlingguy.apache
    - role: geerlingguy.php
