- name: Setup database and and webserver
  hosts: all


  pre_tasks:
    - name: Stop nginx when required
      service:
        name: nginx
        state: stopped
        enabled: false
      ignore_errors: yes

  roles:
    - role: geerlingguy.postgresql
    - role: geerlingguy.apache
    - role: geerlingguy.php
