- name: Create adminer dir
  file:
    path: '{{ adminer_dir }}'
    state: directory

- name: Get Adminer from the Internets
  get_url:
    url: '{{ adminer_src_url }}'
    dest: '{{ adminer_file }}'
